name: delta_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.1.0

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  http: ^0.13.6
  intl: ^0.18.0
  url_launcher: ^6.1.10
  flutter_html: ^3.0.0
  dio: ^5.0.0
  path_provider: ^2.0.0
  open_file: ^3.2.1
  cupertino_icons: ^1.0.8
  photo_view: ^0.14.0
  cached_network_image: ^3.3.1
  lottie: ^3.0.0


dev_dependencies:
  flutter_launcher_icons: ^0.10.0
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/logo.png"
  adaptive_icon_background: "#ffffff"

flutter:
  uses-material-design: true

  assets:
    - assets/images/logo.png
    - assets/images/delta-family-logo.png
    - assets/lottie/announcement.json
    - assets/lottie/noResultFound.json
